spring:
  datasource:                       
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb         
    username: sa                   
    password: '{cipher}98c51a59269b822aa592236fe4226f517b433a41e2e13ce3c9401f1449bb367e'        

token:
  expiration_time: 864000000 #하루짜리 토큰
  secret: user_token_default
gateway:
  ip: 192.168.7.71